version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./:/app
    depends_on:
      - server-database
    environment:
      - DATABASE_URL=mongodb://server-database:27017/ufood
      - PORT=8081
  server-database:
    image: mongo
    ports:
      - 27017:27017
    # If running docker on windows, put in comments the volume because there is an incompatibility between mongo and windows volumes (you will always get connection refused)
    volumes:
      - ./db:/data/db
